import { Type, type Static } from "@sinclair/typebox";
import { CONTRACT_VERSION } from "./constants.js";

/**
 * Browser-owned macOS primary login (ADR 0022).
 *
 * One generic first-party browser grant replaces every per-provider native
 * linking protocol. The native side prepares an anonymous, bounded grant with
 * hashed state/cancel secrets and an S256 challenge; the first-party browser
 * approves it with a live authenticated Web session; the callback carries only
 * opaque attempt/code/state; the fixed WKWebView POST exchanges the code and
 * verifier once for an ordinary device session. Only hashes of proof and
 * cancellation secrets are stored server-side, and no response carries a
 * bearer credential beyond the ordinary session response of the consume call.
 */

const BoundedSecret = Type.String({ minLength: 32, maxLength: 256, pattern: "^[A-Za-z0-9_-]+$" });
/** Exact Web origin, server-derived by the BFF; never client authority. */
const WebOrigin = Type.String({ minLength: 1, maxLength: 200 });

/** Fixed, immutable protocol identity for every grant in this flow. */
export const DESKTOP_BROWSER_LOGIN_PROTOCOL_VERSION = 1 as const;
export const DESKTOP_BROWSER_LOGIN_PURPOSE = "macos-primary-login" as const;

/** Anonymous preparation of one bounded first-party browser grant. */
export const DesktopBrowserLoginPrepareRequestSchema = Type.Object(
  {
    protocol_version: Type.Literal(DESKTOP_BROWSER_LOGIN_PROTOCOL_VERSION),
    purpose: Type.Literal(DESKTOP_BROWSER_LOGIN_PURPOSE),
    /** S256 PKCE challenge generated by the initiating native operation. */
    challenge: BoundedSecret,
    /** Raw CSRF/operation state; only its hash is ever stored. */
    state: BoundedSecret,
    /** Raw cancellation secret; only its hash is ever stored. */
    cancel_secret: BoundedSecret,
    /** Exact allowlisted Web origin that will own the browser confirmation. */
    web_origin: WebOrigin,
  },
  { additionalProperties: false },
);
export type DesktopBrowserLoginPrepareRequest = Static<
  typeof DesktopBrowserLoginPrepareRequestSchema
>;

export const DesktopBrowserLoginPrepareResponseSchema = Type.Object(
  {
    contract_version: Type.Literal(CONTRACT_VERSION),
    /** Opaque grant handle; it is not a bearer credential. */
    attempt_id: Type.String({ format: "uuid" }),
    /** First-party browser authorization entry for this exact grant. */
    authorization_url: Type.String({ minLength: 1, maxLength: 2000 }),
    expires_at: Type.String({ format: "date-time" }),
    /** Human-readable value shown on both Mac and browser; never a proof. */
    matching_hint: Type.String({ minLength: 4, maxLength: 32 }),
  },
  { additionalProperties: false },
);
export type DesktopBrowserLoginPrepareResponse = Static<
  typeof DesktopBrowserLoginPrepareResponseSchema
>;

/** Intentional approval from the authenticated first-party browser session. */
export const DesktopBrowserLoginApproveRequestSchema = Type.Object(
  {
    /** Raw operation state proving this approval belongs to this grant. */
    state: BoundedSecret,
    /** Server-derived deployment origin; it must equal the prepared origin. */
    web_origin: WebOrigin,
  },
  { additionalProperties: false },
);
export type DesktopBrowserLoginApproveRequest = Static<
  typeof DesktopBrowserLoginApproveRequestSchema
>;

export const DesktopBrowserLoginApproveResponseSchema = Type.Object(
  {
    contract_version: Type.Literal(CONTRACT_VERSION),
    attempt_id: Type.String({ format: "uuid" }),
    state: Type.Literal("approved"),
    /** One-use exchange code; null on an idempotent already-approved reply. */
    code: Type.Union([Type.String({ minLength: 32, maxLength: 256 }), Type.Null()]),
    code_expires_at: Type.String({ format: "date-time" }),
    /** Fixed-scheme native callback carrying attempt, code and state only. */
    callback_url: Type.String({ minLength: 1, maxLength: 2000 }),
    matching_hint: Type.String({ minLength: 4, maxLength: 32 }),
    /** Canonical identity the browser session verified at approval time. */
    account_id: Type.String({ format: "uuid" }),
    user_id: Type.String({ format: "uuid" }),
    /** True when a previous approval already minted its single code. */
    already_approved: Type.Boolean(),
  },
  { additionalProperties: false },
);
export type DesktopBrowserLoginApproveResponse = Static<
  typeof DesktopBrowserLoginApproveResponseSchema
>;

/** One-use exchange run inside the selected WKWebView context. */
export const DesktopBrowserLoginConsumeRequestSchema = Type.Object(
  {
    attempt_id: Type.String({ format: "uuid" }),
    code: BoundedSecret,
    /** Raw S256 verifier matching the prepared challenge. */
    verifier: BoundedSecret,
    state: BoundedSecret,
    /** Server-derived deployment origin; it must equal the prepared origin. */
    web_origin: WebOrigin,
  },
  { additionalProperties: false },
);
export type DesktopBrowserLoginConsumeRequest = Static<
  typeof DesktopBrowserLoginConsumeRequestSchema
>;

/** Deliberate cancellation with the prepared cancellation secret. */
export const DesktopBrowserLoginCancelRequestSchema = Type.Object(
  {
    attempt_id: Type.String({ format: "uuid" }),
    cancel_secret: BoundedSecret,
  },
  { additionalProperties: false },
);
export type DesktopBrowserLoginCancelRequest = Static<
  typeof DesktopBrowserLoginCancelRequestSchema
>;

/**
 * Intentional browser decline: authenticated and state-bound like approval,
 * it cancels the grant without ever attaching identity or minting a code.
 */
export const DesktopBrowserLoginDeclineRequestSchema = Type.Object(
  {
    state: BoundedSecret,
    /** Server-derived deployment origin; it must equal the prepared origin. */
    web_origin: WebOrigin,
  },
  { additionalProperties: false },
);
export type DesktopBrowserLoginDeclineRequest = Static<
  typeof DesktopBrowserLoginDeclineRequestSchema
>;

export const DesktopBrowserLoginCancelResponseSchema = Type.Object(
  {
    contract_version: Type.Literal(CONTRACT_VERSION),
    attempt_id: Type.String({ format: "uuid" }),
    state: Type.Union([
      Type.Literal("cancelled"),
      Type.Literal("consumed"),
      Type.Literal("expired"),
    ]),
    cancellation_recorded: Type.Boolean(),
  },
  { additionalProperties: false },
);
export type DesktopBrowserLoginCancelResponse = Static<
  typeof DesktopBrowserLoginCancelResponseSchema
>;

/**
 * Secret-bound read-only result for an unknown exchange outcome. It never
 * mints a session or a code and reveals identity only against a matching
 * proof (PKCE verifier or cancellation secret).
 */
export const DesktopBrowserLoginGrantResultRequestSchema = Type.Object(
  {
    attempt_id: Type.String({ format: "uuid" }),
    verifier: Type.Optional(BoundedSecret),
    cancel_secret: Type.Optional(BoundedSecret),
  },
  { additionalProperties: false },
);
export type DesktopBrowserLoginGrantResultRequest = Static<
  typeof DesktopBrowserLoginGrantResultRequestSchema
>;

export const DesktopBrowserLoginGrantResultResponseSchema = Type.Object(
  {
    contract_version: Type.Literal(CONTRACT_VERSION),
    attempt_id: Type.String({ format: "uuid" }),
    state: Type.Union([
      Type.Literal("prepared"),
      Type.Literal("approved"),
      Type.Literal("consumed"),
      Type.Literal("cancelled"),
      Type.Literal("expired"),
    ]),
    /** Exact approved identity, visible only against a matching proof. */
    account_id: Type.Union([Type.String({ format: "uuid" }), Type.Null()]),
    user_id: Type.Union([Type.String({ format: "uuid" }), Type.Null()]),
    /** True only when the device session was created inside the consume transaction. */
    committed: Type.Boolean(),
    expires_at: Type.String({ format: "date-time" }),
  },
  { additionalProperties: false },
);
export type DesktopBrowserLoginGrantResultResponse = Static<
  typeof DesktopBrowserLoginGrantResultResponseSchema
>;

/**
 * Read-only browser inspection of one pending grant for the confirmation
 * page. It reveals the matching hint and lifecycle state to a signed-in real
 * identity; it never reveals proof material or attaches identity.
 */
export const DesktopBrowserLoginGrantViewSchema = Type.Object(
  {
    contract_version: Type.Literal(CONTRACT_VERSION),
    attempt_id: Type.String({ format: "uuid" }),
    state: Type.Union([
      Type.Literal("prepared"),
      Type.Literal("approved"),
      Type.Literal("consumed"),
      Type.Literal("cancelled"),
      Type.Literal("expired"),
    ]),
    matching_hint: Type.String({ minLength: 4, maxLength: 32 }),
    expires_at: Type.String({ format: "date-time" }),
  },
  { additionalProperties: false },
);
export type DesktopBrowserLoginGrantView = Static<
  typeof DesktopBrowserLoginGrantViewSchema
>;

/**
 * Read-only correlation of the live backend session against one consumed
 * grant. The caller is the normal bearer session created by that grant; a
 * session from any other grant is refused instead of being read back.
 */
export const DesktopBrowserLoginStatusResponseSchema = Type.Object(
  {
    contract_version: Type.Literal(CONTRACT_VERSION),
    attempt_id: Type.String({ format: "uuid" }),
    state: Type.Literal("consumed"),
    account_id: Type.String({ format: "uuid" }),
    user_id: Type.String({ format: "uuid" }),
    device_session_id: Type.String({ format: "uuid" }),
    consumed_at: Type.String({ format: "date-time" }),
  },
  { additionalProperties: false },
);
export type DesktopBrowserLoginStatusResponse = Static<
  typeof DesktopBrowserLoginStatusResponseSchema
>;
